const numberButtons = document.querySelectorAll('[data-number')
const operationButtons = document.querySelectorAll('[data-operation')
const equalsButtons = document.querySelectorAll('[data-equals')
const deleteButtons = document.querySelectorAll('[data-delete')
const allClearButtons = document.querySelectorAll('[data-all-clear')
const previousOperandTextElement = document.querySelector('[data-previous-operand')
const currentOperandTextElement = document.querySelector('[data-current-operand')